services:
 - mysql

stages:
  - build
  - connect
  - test
  - package

variables:
 MYSQL_DATABASE_NAME: qs
 MYSQL_DATABASE_SCHEMA: "$CI_PROJECT_DIR/src/main/resources/static/db.sql" 
 MYSQL_ROOT_PASSWORD: password
 SPRING_DATASOURCE: --spring.datasource.url=jdbc:mysql://mysql:3306/qs?createDatabaseIfNotExist=true

cache:
  paths:
    - .m2/repository
    - node_modules/
  key: "$CI_BUILD_REF_NAME"

install_dependencies:
  image: node:14.15.4
  stage: build
  script:
    - npm install
  artifacts:
    paths:
     - node_modules/

build_backend:
  image: maven:3-jdk-11
  stage: build
  script:
  - mvn clean compile

connect:
  image: mysql
  stage: connect
  needs: ["build_backend"]
  before_script:
  - mysql --version
  - apt-get update -q && apt-get install -qqy --no-install-recommends mysql-client
  script:
  - echo "create database $MYSQL_DATABASE_NAME;" | mysql --user=root --password="$MYSQL_ROOT_PASSWORD" --host=mysql
  - mysql --user=root --password="$MYSQL_ROOT_PASSWORD" --host=mysql $MYSQL_DATABASE_NAME < $MYSQL_DATABASE_SCHEMA
  - mysql --user=root --password="$MYSQL_ROOT_PASSWORD" --host=mysql -e "show databases; use $MYSQL_DATABASE_NAME; show tables;"


#test_front:
#  image: node:14.15.4
#  stage: test
#  needs: ["install_dependencies"]
#  script:
#    - npm run test

test_back:
  image: maven:3-jdk-11
  stage: test
  needs: ["connect"]
  script:
    - mvn test $SPRING_DATASOURCE

package:
    image: maven:3-jdk-11
    stage: package
    needs: ["test_back"]
    script:
      - mvn -DskipTests package $SPRING_DATASOURCE
#    only:
#      - main