stages:
  - frontend
  - backend

cache:
  paths:
    - .m2/repository
    - node_modules/
  key: "$CI_BUILD_REF_NAME"

install_dependencies:
  image: node:14.15.4
  stage: frontend
  script:
    - npm install
  artifacts:
    paths:
     - node_modules/

test_front:
  image: node:14.15.4
  stage: frontend
  needs: ["install_dependencies"]
  script:
    - npm run test

test_back:
  image: maven:3-jdk-11
  stage: backend
  script:
    - mvn clean test

package:
    image: maven:3-jdk-11
    stage: backend
    needs: ["test_back"]
    script:
      - mvn -DskipTests package
    only:
      - main